/**
 * Invoices.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.acme.service.soap ;

public class Invoices implements java.io.Serializable
{
    private Integer account ;
    private Double amount ;
    private Integer branch ;
    private Integer department ;
    private Integer line ;
    private Double units ;

    /**
     * Sets the account value for this Invoices.
     *
     * @param account
     */
    public void setAccount ( Integer account )
    {
        this.account = account ;
    }

    /**
     * Gets the account value for this Invoices.
     *
     * @return account
     */
    public Integer getAccount ()
    {
        return account ;
    }

    /**
     * Sets the amount value for this Invoices.
     *
     * @param amount
     */
    public void setAmount ( Double amount )
    {
        this.amount = amount ;
    }

    /**
     * Gets the amount value for this Invoices.
     *
     * @return amount
     */
    public Double getAmount ()
    {
        return amount ;
    }

    /**
     * Sets the branch value for this Invoices.
     *
     * @param branch
     */
    public void setBranch ( Integer branch )
    {
        this.branch = branch ;
    }

    /**
     * Gets the branch value for this Invoices.
     *
     * @return branch
     */
    public Integer getBranch ()
    {
        return branch ;
    }

    /**
     * Sets the department value for this Invoices.
     *
     * @param department
     */
    public void setDepartment ( Integer department )
    {
        this.department = department ;
    }

    /**
     * Gets the department value for this Invoices.
     *
     * @return department
     */
    public Integer getDepartment ()
    {
        return department ;
    }

    /**
     * Sets the line value for this Invoices.
     *
     * @param line
     */
    public void setLine ( Integer line )
    {
        this.line = line ;
    }

    /**
     * Gets the line value for this Invoices.
     *
     * @return line
     */
    public Integer getLine ()
    {
        return line ;
    }

    /**
     * Sets the units value for this Invoices.
     *
     * @param units
     */
    public void setUnits ( Double units )
    {
        this.units = units ;
    }

    /**
     * Gets the units value for this Invoices.
     *
     * @return units
     */
    public Double getUnits ()
    {
        return units ;
    }

    /*
        Apache Axis Meta-Data
    */

    private static org.apache.axis.description.TypeDesc typeDesc = new org.apache.axis.description.TypeDesc ( Invoices.class, true ) ; 

    static
    {
        typeDesc.setXmlType ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "Invoices" ) ) ;

        org.apache.axis.description.ElementDesc elemField = null ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "account" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "account" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "int" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "amount" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "amount" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "double" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "branch" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "branch" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "int" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "department" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "department" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "int" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "line" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "line" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "int" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "units" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://soap.service.acme.com", "units" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "double" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;
    }

    public static org.apache.axis.description.TypeDesc getTypeDesc ()
    {
        return typeDesc ;
    }

    public static org.apache.axis.encoding.Serializer getSerializer ( java.lang.String _mechType, java.lang.Class _javaType, javax.xml.namespace.QName _xmlType )
    {
        return new org.apache.axis.encoding.ser.BeanSerializer ( _javaType, _xmlType, typeDesc ) ;
    }

    public static org.apache.axis.encoding.Deserializer getDeserializer ( java.lang.String _mechType, java.lang.Class _javaType, javax.xml.namespace.QName _xmlType )
    {
        return new org.apache.axis.encoding.ser.BeanDeserializer ( _javaType, _xmlType, typeDesc ) ;
    }
}
