/**
 * ProcessMakertoLANSAService.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.acme.service.soap ;

public class ProcessMakertoLANSAService implements com.lansa.jsm.service.SOAPServerHandler
{

    /*
        Parameter Prepare - SetEmployeeTerminationDate ( EmployeeNumber )
    */

    public final void prepareParameter_SETEMPLOYEETERMINATIONDATE_EMPLOYEENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - SetEmployeeTerminationDate ( EmployeeNumber )
    */

    public final void getParameter_SETEMPLOYEETERMINATIONDATE_EMPLOYEENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "EMPNO", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - SetEmployeeTerminationDate ( TerminationDate )
    */

    public final void prepareParameter_SETEMPLOYEETERMINATIONDATE_TERMINATIONDATE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - SetEmployeeTerminationDate ( TerminationDate )
    */

    public final void getParameter_SETEMPLOYEETERMINATIONDATE_TERMINATIONDATE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_TERMDATE", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - SetEmployeeTerminationDate ( ProcessMakerCaseNumber )
    */

    public final void prepareParameter_SETEMPLOYEETERMINATIONDATE_PROCESSMAKERCASENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - SetEmployeeTerminationDate ( ProcessMakerCaseNumber )
    */

    public final void getParameter_SETEMPLOYEETERMINATIONDATE_PROCESSMAKERCASENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CASENUMBER", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - SetEmployeeTerminationDate ( TerminationReason )
    */

    public final void prepareParameter_SETEMPLOYEETERMINATIONDATE_TERMINATIONREASON ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - SetEmployeeTerminationDate ( TerminationReason )
    */

    public final void getParameter_SETEMPLOYEETERMINATIONDATE_TERMINATIONREASON ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_TERMREASON", parameter.getEntity ( null ) ) ;
    }

    /*
        Return Parameter Prepare - SetEmployeeTerminationDate
    */

    public final void prepareReturn_SETEMPLOYEETERMINATIONDATE ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
        response.prepareParameter ( java.lang.String.class, false, false ) ;
    }

    /*
        Return Parameter Set - SetEmployeeTerminationDate
    */

    public final void setReturn_SETEMPLOYEETERMINATIONDATE ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "PM_TERMRET" ), null, null ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( processID )
    */

    public final void prepareParameter_UPDATEINVOICES_PROCESSID ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( processID )
    */

    public final void getParameter_UPDATEINVOICES_PROCESSID ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_PROCESSID", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( caseID )
    */

    public final void prepareParameter_UPDATEINVOICES_CASEID ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( caseID )
    */

    public final void getParameter_UPDATEINVOICES_CASEID ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CASEID", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( control )
    */

    public final void prepareParameter_UPDATEINVOICES_CONTROL ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( control )
    */

    public final void getParameter_UPDATEINVOICES_CONTROL ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "AICTRL", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( company )
    */

    public final void prepareParameter_UPDATEINVOICES_COMPANY ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( company )
    */

    public final void getParameter_UPDATEINVOICES_COMPANY ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "COMPANY", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( partition )
    */

    public final void prepareParameter_UPDATEINVOICES_PARTITION ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( partition )
    */

    public final void getParameter_UPDATEINVOICES_PARTITION ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PARTITION", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( caseNumber )
    */

    public final void prepareParameter_UPDATEINVOICES_CASENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( caseNumber )
    */

    public final void getParameter_UPDATEINVOICES_CASENUMBER ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CASENUMBER", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( casePIN )
    */

    public final void prepareParameter_UPDATEINVOICES_CASEPIN ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( casePIN )
    */

    public final void getParameter_UPDATEINVOICES_CASEPIN ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CASEPIN", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( createUser )
    */

    public final void prepareParameter_UPDATEINVOICES_CREATEUSER ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( createUser )
    */

    public final void getParameter_UPDATEINVOICES_CREATEUSER ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CREATEUSER", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( approveUser )
    */

    public final void prepareParameter_UPDATEINVOICES_APPROVEUSER ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( approveUser )
    */

    public final void getParameter_UPDATEINVOICES_APPROVEUSER ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_APPROVEUSER", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( bemsMessageQ )
    */

    public final void prepareParameter_UPDATEINVOICES_BEMSMESSAGEQ ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( bemsMessageQ )
    */

    public final void getParameter_UPDATEINVOICES_BEMSMESSAGEQ ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_MESSAGEQ", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( bemsMessage )
    */

    public final void prepareParameter_UPDATEINVOICES_BEMSMESSAGE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( bemsMessage )
    */

    public final void getParameter_UPDATEINVOICES_BEMSMESSAGE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_MESSAGE", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( bemsObject )
    */

    public final void prepareParameter_UPDATEINVOICES_BEMSOBJECT ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( bemsObject )
    */

    public final void getParameter_UPDATEINVOICES_BEMSOBJECT ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_BEMSOBJECT", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoices ( bemsCommand )
    */

    public final void prepareParameter_UPDATEINVOICES_BEMSCOMMAND ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoices ( bemsCommand )
    */

    public final void getParameter_UPDATEINVOICES_BEMSCOMMAND ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_BEMSCOMMAND", parameter.getEntity ( null ) ) ;
    }

    /*
        Return Parameter Prepare - updateInvoices
    */

    public final void prepareReturn_UPDATEINVOICES ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
        response.prepareParameter ( java.lang.String.class, false, false ) ;
    }

    /*
        Return Parameter Set - updateInvoices
    */

    public final void setReturn_UPDATEINVOICES ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "PM_STATUSCODE" ), null, null ) ;
    }
}
