/**
 * ProcessMakertoLANSAProvider.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.acme.service.soap ;

public interface ProcessMakertoLANSAProvider
{
    public String SetEmployeeTerminationDate ( String EmployeeNumber, String TerminationDate, String ProcessMakerCaseNumber, String TerminationReason ) ;
    public String updateInvoices ( String processID, String caseID, String control, String company, String partition, String caseNumber, String casePIN, String createUser, String approveUser, String bemsMessageQ, String bemsMessage, String bemsObject, String bemsCommand ) ;
}
