/**
 * UHAEmployeeAgentService.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.UHAcompany.service.soap ;

public class UHAEmployeeAgentService implements com.lansa.jsm.service.SOAPAgentHandler
{

    /*
        Operation - getEmployees
    */

    public final void setOperation_GETEMPLOYEES ()
    {
    }

    /*
        Operation Request - getEmployees
    */

    public final void prepareRequest_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request ) throws Exception
    {
        request.prepareParameter ( "DEPARTMENTCODE", java.lang.String.class, false, false ) ;
        request.prepareParameter ( "SECTIONCODE", java.lang.String.class, false, false ) ;
    }

    /*
        Operation Parameter - getEmployees
    */

    public final void setParameter_GETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "DEPTMENT" ), null, null ) ;
    }

    /*
        Operation Parameter - getEmployees
    */

    public final void setParameter_GETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "SECTION" ), null, null ) ;
    }

    /*
        Operation Response - getEmployees
    */

    public final void prepareResponse_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response ) throws Exception
    {
        response.prepareFragment ( new String[] { "RESPONSE" }, com.UHAcompany.service.soap.Employee.class, true, true, null ) ;
    }

    /*
        Operation Fragment - getEmployees
    */

    public final void getFragment_GETEMPLOYEES_RESPONSE ( com.lansa.jsm.service.SOAPAgentResponseFragment fragment, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        bind.setFieldValue ( "EMPNO", fragment.getEntity ( "employeeID", null ) ) ;
        bind.setFieldValue ( "GIVENAME", fragment.getEntity ( "firstName", null ) ) ;
        bind.setFieldValue ( "SALARY", fragment.getEntity ( "salary", null ) ) ;
        bind.setFieldValue ( "SURNAME", fragment.getEntity ( "surName", null ) ) ;
    }

    /*
        Operation Return - getEmployees
    */

    public final void getReturnParameter_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
    }

    /*
        Operation Call - getEmployees
    */

    public final com.lansa.jsm.service.SOAPAgentResponse callOperation_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request, String user, String password, String url ) throws Exception
    {
        com.UHAcompany.service.soap.UHAEmployeeServerServiceServiceLocator locator = new com.UHAcompany.service.soap.UHAEmployeeServerServiceServiceLocator () ;

        String endPoint = locator.getUHAEmployeeServerServicePortAddress () ;

        if ( url != null )
        {
            endPoint = url ;
        }

        com.UHAcompany.service.soap.UHAEmployeeServerServiceBindingStub stub = (com.UHAcompany.service.soap.UHAEmployeeServerServiceBindingStub)locator.getUHAEmployeeServerServicePort ( new java.net.URL ( endPoint ) ) ;

        if ( user != null && password != null )
        {
            stub.setUsername ( user ) ;

            stub.setPassword ( password ) ;
        }

        /* No include file AGENT_INCLUDE.TXT */

        request.traceStub ( stub ) ;

        return new com.lansa.jsm.service.SOAPAgentResponse ( stub.getEmployees( request.getParameterValueString ( "DEPARTMENTCODE" ), request.getParameterValueString ( "SECTIONCODE" ) ) ) ;
    }
}
