/**
 * UHAEmployeeServerServiceBindingStubAccessor.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.UHAcompany.service.soap ;

public class UHAEmployeeServerServiceBindingStubAccessor implements com.lansa.jsf.soapwizard.LUXOperationAccessor
{
    public org.apache.axis.description.OperationDesc[] getOperations ()
    {
        return UHAEmployeeServerServiceBindingStub._operations ;
    }

    public java.lang.Class getStubClass ()
    {
        return UHAEmployeeServerServiceBindingStub.class ;
    }
}
