/**
 * ProcessMakerServiceSoapStubAccessor.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.processmaker.www ;

public class ProcessMakerServiceSoapStubAccessor implements com.lansa.jsf.soapwizard.LUXOperationAccessor
{
    public org.apache.axis.description.OperationDesc[] getOperations ()
    {
        return ProcessMakerServiceSoapStub._operations ;
    }

    public java.lang.Class getStubClass ()
    {
        return ProcessMakerServiceSoapStub.class ;
    }
}
