/**
 * PMGLInvoiceService.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.acme.service.soap ;

public class PMGLInvoiceService implements com.lansa.jsm.service.SOAPServerHandler
{

    /*
        Parameter Prepare - updateInvoice ( processID )
    */

    public final void prepareParameter_UPDATEINVOICE_PROCESSID ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoice ( processID )
    */

    public final void getParameter_UPDATEINVOICE_PROCESSID ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_PROCESSID", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoice ( caseID )
    */

    public final void prepareParameter_UPDATEINVOICE_CASEID ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - updateInvoice ( caseID )
    */

    public final void getParameter_UPDATEINVOICE_CASEID ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "PM_CASEID", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - updateInvoice ( invoice )
    */

    public final void prepareParameter_UPDATEINVOICE_INVOICE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
        parameter.prepareFragment ( new String[] { "NEWINVOICEREQUEST" }, Invoices.class, true, true, null ) ;
    }

    /*
        Parameter Get - updateInvoice ( invoice )
    */

    public final void getParameter_UPDATEINVOICE_INVOICE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
    }

    /*
        Fragment Get - updateInvoice ( invoice )
    */

    public final void getFragment_UPDATEINVOICE_INVOICE_NEWINVOICEREQUEST ( com.lansa.jsm.service.SOAPServerParameterFragment fragment, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "AICTRL", fragment.getEntity ( "control", null ) ) ;
    }

    /*
        Return Parameter Prepare - updateInvoice
    */

    public final void prepareReturn_UPDATEINVOICE ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
        response.prepareParameter ( java.lang.String.class, false, false ) ;
    }

    /*
        Return Parameter Set - updateInvoice
    */

    public final void setReturn_UPDATEINVOICE ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "PM_STATUSCODE" ), null, null ) ;
    }
}
