/**
 * PMGLInvoiceProvider.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.acme.service.soap ;

public interface PMGLInvoiceProvider
{
    public String updateInvoice ( String processID, String caseID, Invoices[] invoice ) ;
}
