/**
 * UHAEmployeeAgentService.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.lansa.UHASOAPAgent.Tutorial ;

public class UHAEmployeeAgentService implements com.lansa.jsm.service.SOAPAgentHandler
{

    /*
        Operation - getEmployees
    */

    public final void setOperation_GETEMPLOYEES ()
    {
    }

    /*
        Operation Request - getEmployees
    */

    public final void prepareRequest_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request ) throws Exception
    {
        request.prepareParameter ( "DEPARTMENT_CODE", java.lang.String.class, false, false ) ;
        request.prepareParameter ( "SECTION_CODE", java.lang.String.class, false, false ) ;
    }

    /*
        Operation Parameter - getEmployees
    */

    public final void setParameter_GETEMPLOYEES_DEPARTMENT_CODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "DEPTMENT" ), null, null ) ;
    }

    /*
        Operation Parameter - getEmployees
    */

    public final void setParameter_GETEMPLOYEES_SECTION_CODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "SECTION" ), null, null ) ;
    }

    /*
        Operation Response - getEmployees
    */

    public final void prepareResponse_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response ) throws Exception
    {
        response.prepareFragment ( new String[] { "EMPLOYEE" }, com.lansa.UHASOAPServer.Tutorial.Employee.class, true, true, null ) ;
    }

    /*
        Operation Fragment - getEmployees
    */

    public final void getFragment_GETEMPLOYEES_EMPLOYEE ( com.lansa.jsm.service.SOAPAgentResponseFragment fragment, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        bind.setFieldValue ( "EMPNO", fragment.getEntity ( "employee_ID", null ) ) ;
        bind.setFieldValue ( "GIVENAME", fragment.getEntity ( "firstname", null ) ) ;
        bind.setFieldValue ( "SALARY", fragment.getEntity ( "salary", null ) ) ;
        bind.setFieldValue ( "SURNAME", fragment.getEntity ( "surname", null ) ) ;
    }

    /*
        Operation Return - getEmployees
    */

    public final void getReturnParameter_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
    }

    /*
        Operation Call - getEmployees
    */

    public final com.lansa.jsm.service.SOAPAgentResponse callOperation_GETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request, String user, String password, String url ) throws Exception
    {
        com.lansa.UHASOAPServer.Tutorial.UHAEmployeeServerServiceServiceLocator locator = new com.lansa.UHASOAPServer.Tutorial.UHAEmployeeServerServiceServiceLocator () ;

        String endPoint = locator.getUHAEmployeeServerServicePortAddress () ;

        if ( url != null )
        {
            endPoint = url ;
        }

        com.lansa.UHASOAPServer.Tutorial.UHAEmployeeServerServiceBindingStub stub = (com.lansa.UHASOAPServer.Tutorial.UHAEmployeeServerServiceBindingStub)locator.getUHAEmployeeServerServicePort ( new java.net.URL ( endPoint ) ) ;

        if ( user != null && password != null )
        {
            stub.setUsername ( user ) ;

            stub.setPassword ( password ) ;
        }

        /* No include file AGENT_INCLUDE.TXT */

        request.traceStub ( stub ) ;

        return new com.lansa.jsm.service.SOAPAgentResponse ( stub.getEmployees( request.getParameterValueString ( "DEPARTMENT_CODE" ), request.getParameterValueString ( "SECTION_CODE" ) ) ) ;
    }
}
