/**
 * MEF_Test_InterfaceStubAccessor.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package org.tempuri ;

public class MEF_Test_InterfaceStubAccessor implements com.lansa.jsf.soapwizard.LUXOperationAccessor
{
    public org.apache.axis.description.OperationDesc[] getOperations ()
    {
        return MEF_Test_InterfaceStub._operations ;
    }

    public java.lang.Class getStubClass ()
    {
        return MEF_Test_InterfaceStub.class ;
    }
}
