/**
 * UHAEmployeeServerProvider.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.UHAcompany.service.soap ;

public interface UHAEmployeeServerProvider
{
    public void noop (  ) ;
    public Employee[] getEmployees ( String departmentCode, String sectionCode ) ;
}
