/**
 * UHAEmployeeServerProviderStub.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.UHAcompany.service.soap ;

public class UHAEmployeeServerProviderStub implements com.lansa.jsm.service.SOAPServerProviderStub, UHAEmployeeServerProvider
{
    private final static com.lansa.jsm.service.SOAPServerProviderProperties m_providerProperties = new com.lansa.jsm.service.SOAPServerProviderProperties () ; 

    public final static com.lansa.jsm.service.SOAPServerProviderProperties getProviderProperties ()
    {
        return m_providerProperties ;
    }

    static
    {
        m_providerProperties.setStyle ( "wrapped" ) ;
        m_providerProperties.setTypeMappingVersion ( "1.2" ) ;
        m_providerProperties.addReturnType ( "NOOP", null ) ;
        m_providerProperties.addReturnType ( "GETEMPLOYEES", new javax.xml.namespace.QName ( "http://soap.service.UHAcompany.com", "Employee" ) ) ;
    }

    private com.lansa.jsm.service.SOAPServerParameter[] m_parameterArray = null ;

    /*
        Stub implementation
    */

    public final String getProviderMethods ()
    {
        return "noop,getEmployees" ;
    }

    public final Class[] getProviderClasses ()
    {
        return new Class[] { com.UHAcompany.service.soap.Employee.class } ;
    }

    public final com.lansa.jsm.service.SOAPServerParameter[] getProviderParameters ()
    {
        if ( m_parameterArray == null )
        {
            throw new IllegalArgumentException ( getClass().getName() + ": no parameters" ) ;
        }

        return m_parameterArray ;
    }

    /*
        Service implementation
    */

    public final void noop (  )
    {
        m_parameterArray = new com.lansa.jsm.service.SOAPServerParameter[0] ;


        
    }

    public final Employee[] getEmployees ( String departmentCode, String sectionCode )
    {
        m_parameterArray = new com.lansa.jsm.service.SOAPServerParameter[2] ;

        m_parameterArray[0] = new com.lansa.jsm.service.SOAPServerParameter ( "DEPARTMENTCODE", departmentCode ) ;
        m_parameterArray[1] = new com.lansa.jsm.service.SOAPServerParameter ( "SECTIONCODE", sectionCode ) ;

        return null ;
    }
}
