/**
 * UHAEmployeeServerService.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.UHAcompany.service.soap ;

public class UHAEmployeeServerService implements com.lansa.jsm.service.SOAPServerHandler
{

    /*
        Return Parameter Prepare - noop
    */

    public final void prepareReturn_NOOP ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
    }

    /*
        Return Parameter Set - noop
    */

    public final void setReturn_NOOP ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
    }

    /*
        Parameter Prepare - getEmployees ( departmentCode )
    */

    public final void prepareParameter_GETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - getEmployees ( departmentCode )
    */

    public final void getParameter_GETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "DEPTMENT", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - getEmployees ( sectionCode )
    */

    public final void prepareParameter_GETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - getEmployees ( sectionCode )
    */

    public final void getParameter_GETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "SECTION", parameter.getEntity ( null ) ) ;
    }

    /*
        Return Parameter Prepare - getEmployees
    */

    public final void prepareReturn_GETEMPLOYEES ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
        response.prepareParameter ( Employee.class, true, true ) ;
        response.prepareFragment ( new String[] { "EMPLOYEE" }, Employee.class, true, true, null ) ;
    }

    /*
        Return Parameter Set - getEmployees
    */

    public final void setReturn_GETEMPLOYEES ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
    }

    /*
        Fragment Set - getEmployees
    */

    public final void setFragment_GETEMPLOYEES_EMPLOYEE ( com.lansa.jsm.service.SOAPServerResponseFragment fragment, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        fragment.setEntity ( "employeeID", bind.getFieldValue ( "EMPNO" ), null, null ) ;
        fragment.setEntity ( "firstName", bind.getFieldValue ( "GIVENAME" ), null, null ) ;
        fragment.setEntity ( "salary", bind.getFieldValue ( "SALARY" ), null, null ) ;
        fragment.setEntity ( "surname", bind.getFieldValue ( "SURNAME" ), null, null ) ;
    }
}
