/**
 * MLQPRO05_responseService.java
 *
 * This file was generated by LANSA Integrator XMLBind Wizard
 */
package com.mlqlansa.service.xml ;

public class MLQPRO05_responseService implements com.lansa.jsm.service.XMLBindHandler
{

    /*
        Prepare inbound
    */

    public final void prepareInbound ( com.lansa.jsm.service.XMLBindMap map )
    {
    }

    /*
        Prepare outbound
    */

    public final void prepareOutbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;
        map.addDeclaration ( "xml", "http://www.w3.org/XML/1998/namespace", "/DepartmentListResponse" ) ;

        prepareOutboundListsAndFragments ( map ) ;

        prepareOutboundFields ( map ) ;

        prepareOutboundOrder ( map ) ;
    }

    /*
        Prepare outbound lists and fragments
    */

    private final void prepareOutboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "DEPARTMENTLISTRESPONSE" }, null, null, "", "", "", false, true, false, false, "/DepartmentListResponse" ) ;
        map.addList ( new String[] { "DEPARTMENTLISTRESPONSE", "DEPARTMENT" }, null, null, "", "", "", false, true, false, false, "/DepartmentListResponse/Department" ) ;
    }

    /*
        Prepare outbound fields
    */

    private final void prepareOutboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "DEPARTMENTLISTRESPONSE" }, "STD_TEXTS", null, "", "", "", false, true, false, false, "/DepartmentListResponse/ReverseString" ) ;
        map.addField ( new String[] { "DEPARTMENTLISTRESPONSE", "DEPARTMENT" }, "DEPTMENT", null, "", "", "", false, true, false, false, "/DepartmentListResponse/Department/Code" ) ;
        map.addField ( new String[] { "DEPARTMENTLISTRESPONSE", "DEPARTMENT" }, "DEPTDESC", null, "", "", "", false, true, false, false, "/DepartmentListResponse/Department/Description" ) ;
    }

    /*
        Prepare outbound order
    */

    private final void prepareOutboundOrder ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addOrder ( "/DepartmentListResponse" ) ;
        map.addOrder ( "/DepartmentListResponse/ReverseString" ) ;
        map.addOrder ( "/DepartmentListResponse/Department" ) ;
        map.addOrder ( "/DepartmentListResponse/Department/Code" ) ;
        map.addOrder ( "/DepartmentListResponse/Department/Description" ) ;
    }
}
