/**
 * MLQEmployeeAgentService.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.lansa.SOAPAgent.tutorial ;

public class MLQEmployeeAgentService implements com.lansa.jsm.service.SOAPAgentHandler
{

    /*
        Operation - MLQGetEmployees
    */

    public final void setOperation_MLQGETEMPLOYEES ()
    {
    }

    /*
        Operation Request - MLQGetEmployees
    */

    public final void prepareRequest_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request ) throws Exception
    {
        request.prepareParameter ( "DEPARTMENTCODE", java.lang.String.class, false, false ) ;
        request.prepareParameter ( "SECTIONCODE", java.lang.String.class, false, false ) ;
    }

    /*
        Operation Parameter - MLQGetEmployees
    */

    public final void setParameter_MLQGETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "DEPTMENT" ), null, null ) ;
    }

    /*
        Operation Parameter - MLQGetEmployees
    */

    public final void setParameter_MLQGETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "SECTION" ), null, null ) ;
    }

    /*
        Operation Response - MLQGetEmployees
    */

    public final void prepareResponse_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response ) throws Exception
    {
        response.prepareFragment ( new String[] { "EMPLOYEE" }, com.lansa.SOAPServer.mlqtutorial.EMPLOYEE.class, true, true, null ) ;
    }

    /*
        Operation Fragment - MLQGetEmployees
    */

    public final void getFragment_MLQGETEMPLOYEES_EMPLOYEE ( com.lansa.jsm.service.SOAPAgentResponseFragment fragment, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        bind.setFieldValue ( "EMPNO", fragment.getEntity ( "employeeID", null ) ) ;
        bind.setFieldValue ( "GIVENAME", fragment.getEntity ( "firstName", null ) ) ;
        bind.setFieldValue ( "SURNAME", fragment.getEntity ( "lastName", null ) ) ;
        bind.setFieldValue ( "SALARY", fragment.getEntity ( "salary", null ) ) ;
    }

    /*
        Operation Return - MLQGetEmployees
    */

    public final void getReturnParameter_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentResponse response, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
    }

    /*
        Operation Call - MLQGetEmployees
    */

    public final com.lansa.jsm.service.SOAPAgentResponse callOperation_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPAgentRequest request, String user, String password, String url ) throws Exception
    {
        com.lansa.SOAPServer.mlqtutorial.MLQEmployeeServerServiceServiceLocator locator = new com.lansa.SOAPServer.mlqtutorial.MLQEmployeeServerServiceServiceLocator () ;

        String endPoint = locator.getMLQEmployeeServerServicePortAddress () ;

        if ( url != null )
        {
            endPoint = url ;
        }

        com.lansa.SOAPServer.mlqtutorial.MLQEmployeeServerServiceBindingStub stub = (com.lansa.SOAPServer.mlqtutorial.MLQEmployeeServerServiceBindingStub)locator.getMLQEmployeeServerServicePort ( new java.net.URL ( endPoint ) ) ;

        if ( user != null && password != null )
        {
            stub.setUsername ( user ) ;

            stub.setPassword ( password ) ;
        }

        /* No include file AGENT_INCLUDE.TXT */

        request.traceStub ( stub ) ;

        return new com.lansa.jsm.service.SOAPAgentResponse ( stub.MLQGetEmployees( request.getParameterValueString ( "DEPARTMENTCODE" ), request.getParameterValueString ( "SECTIONCODE" ) ) ) ;
    }
}
