/**
 * NewSubmissionService.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.acme.service.soap ;

public class NewSubmissionService implements com.lansa.jsm.service.SOAPAgentHandler
{

    /*
        Operation - NewSubmission
    */

    public final void setOperation_NEWSUBMISSION ()
    {
    }

    /*
        Operation Request - NewSubmission
    */

    public final void prepareRequest_NEWSUBMISSION ( com.lansa.jsm.service.SOAPAgentRequest request ) throws Exception
    {
        request.prepareParameter ( "USERNAME", java.lang.String.class, false, false ) ;
        request.prepareParameter ( "PASSWORD", java.lang.String.class, false, false ) ;
        request.prepareParameter ( "FILE", byte.class, true, false ) ;
    }

    /*
        Operation Parameter - NewSubmission
    */

    public final void setParameter_NEWSUBMISSION_USERNAME ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( bind.getFieldValue ( "WK_USER" ), null, null ) ;
    }

    /*
        Operation Parameter - NewSubmission
    */

    public final void setParameter_NEWSUBMISSION_PASSWORD ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setEntity ( "WK_PASS", null, null ) ;
    }

    /*
        Operation Parameter - NewSubmission
    */

    public final void setParameter_NEWSUBMISSION_FILE ( com.lansa.jsm.service.SOAPAgentParameter parameter, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        parameter.setStreamFile ( bind.getFieldValue ( "XMLREQ" ) ) ;
    }

    /*
        Operation Response - NewSubmission
    */

    public final void prepareResponse_NEWSUBMISSION ( com.lansa.jsm.service.SOAPAgentResponse response ) throws Exception
    {
    }

    /*
        Operation Return - NewSubmission
    */

    public final void getReturnParameter_NEWSUBMISSION ( com.lansa.jsm.service.SOAPAgentResponse response, com.lansa.jsm.service.SOAPAgentBind bind ) throws Exception
    {
        bind.setStreamFile ( "XMLRSP", response.getValueObject () ) ;
    }

    /*
        Operation Call - NewSubmission
    */

    public final com.lansa.jsm.service.SOAPAgentResponse callOperation_NEWSUBMISSION ( com.lansa.jsm.service.SOAPAgentRequest request, String user, String password, String url ) throws Exception
    {
        org.tempuri.MEF_TestLocator locator = new org.tempuri.MEF_TestLocator () ;

        String endPoint = locator.getMEF_Test_InterfaceAddress () ;

        if ( url != null )
        {
            endPoint = url ;
        }

        org.tempuri.MEF_Test_InterfaceStub stub = (org.tempuri.MEF_Test_InterfaceStub)locator.getMEF_Test_Interface ( new java.net.URL ( endPoint ) ) ;

        if ( user != null && password != null )
        {
            stub.setUsername ( user ) ;

            stub.setPassword ( password ) ;
        }

        /* No include file AGENT_INCLUDE.TXT */

        request.traceStub ( stub ) ;

        return new com.lansa.jsm.service.SOAPAgentResponse ( stub.newSubmission( request.getParameterValueString ( "USERNAME" ), request.getParameterValueString ( "PASSWORD" ), request.getParameterValueByteArray ( "FILE" ) ) ) ;
    }
}
