/**
 * MLQPRO05_requestService.java
 *
 * This file was generated by LANSA Integrator XMLBind Wizard
 */
package com.mlqlansa.service.xml ;

public class MLQPRO05_requestService implements com.lansa.jsm.service.XMLBindHandler
{

    /*
        Prepare inbound
    */

    public final void prepareInbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;

        prepareInboundListsAndFragments ( map ) ;

        prepareInboundFields ( map ) ;
    }

    /*
        Prepare inbound lists and fragments
    */

    private final void prepareInboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "DEPARTMENTLISTREQUEST" }, null, null, "", "", "", false, true, false, false, "/DepartmentListRequest" ) ;
        map.addList ( new String[] { "DEPARTMENTLISTREQUEST", "DEPARTMENT" }, null, null, "", "", "", false, true, false, false, "/DepartmentListRequest/Department" ) ;
    }

    /*
        Prepare inbound fields
    */

    private final void prepareInboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "DEPARTMENTLISTREQUEST" }, "STD_TEXTS", null, "", "", "", false, true, false, false, "/DepartmentListRequest/ReverseString" ) ;
        map.addField ( new String[] { "DEPARTMENTLISTREQUEST", "DEPARTMENT" }, "DEPTMENT", null, "", "", "", false, true, false, false, "/DepartmentListRequest/Department/Code" ) ;
    }

    /*
        Prepare outbound
    */

    public final void prepareOutbound ( com.lansa.jsm.service.XMLBindMap map )
    {
    }
}
