/**
 * MLQPRO04_responseService.java
 *
 * This file was generated by LANSA Integrator XMLBind Wizard
 */
package com.mlqlansa.service.xml ;

public class MLQPRO04_responseService implements com.lansa.jsm.service.XMLBindHandler
{

    /*
        Prepare inbound
    */

    public final void prepareInbound ( com.lansa.jsm.service.XMLBindMap map )
    {
    }

    /*
        Prepare outbound
    */

    public final void prepareOutbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;
        map.addDeclaration ( "xml", "http://www.w3.org/XML/1998/namespace", "/DepartmentResponse" ) ;

        prepareOutboundListsAndFragments ( map ) ;

        prepareOutboundFields ( map ) ;

        prepareOutboundOrder ( map ) ;
    }

    /*
        Prepare outbound lists and fragments
    */

    private final void prepareOutboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "DEPARTMENTRESPONSE" }, null, null, "", "", "", false, true, false, false, "/DepartmentResponse" ) ;
    }

    /*
        Prepare outbound fields
    */

    private final void prepareOutboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "DEPARTMENTRESPONSE" }, "DEPTDESC", null, "", "", "", false, true, false, false, "/DepartmentResponse/DepartmentDescription" ) ;
    }

    /*
        Prepare outbound order
    */

    private final void prepareOutboundOrder ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addOrder ( "/DepartmentResponse" ) ;
        map.addOrder ( "/DepartmentResponse/DepartmentDescription" ) ;
    }
}
