/**
 * AddEmployeeService.java
 *
 * This file was generated by LANSA Integrator XMLBind Wizard
 */
package com.acme.service.xml ;

public class AddEmployeeService implements com.lansa.jsm.service.XMLBindHandler
{

    /*
        Prepare inbound
    */

    public final void prepareInbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;

        prepareInboundListsAndFragments ( map ) ;

        prepareInboundFields ( map ) ;
    }

    /*
        Prepare inbound lists and fragments
    */

    private final void prepareInboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "WORKFLOW" }, null, null, "", "", "", false, true, false, false, "/workflow" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "IDENTIFIER" }, null, null, "", "", "", false, true, false, false, "/workflow/identifier" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "BEMS" }, null, null, "", "", "", false, true, false, false, "/workflow/BEMS" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "DATA" }, null, null, "", "", "", false, true, false, false, "/workflow/data" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, null, null, "", "", "", false, true, false, false, "/workflow/data/Employee" ) ;
    }

    /*
        Prepare inbound fields
    */

    private final void prepareInboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWOBJ", null, "", "", "", false, true, false, false, "/workflow/identifier/Object" ) ;
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWEVT", null, "", "", "", false, true, false, false, "/workflow/identifier/Event" ) ;
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWWNME", null, "", "", "", false, true, false, false, "/workflow/identifier/Workflow" ) ;
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWCID", null, "", "", "", false, true, false, false, "/workflow/identifier/Case_Number" ) ;
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWUSR", null, "", "", "", false, true, false, false, "/workflow/identifier/Workflow_User" ) ;
        map.addField ( new String[] { "WORKFLOW", "IDENTIFIER" }, "PMWDTM", null, "", "", "", false, true, false, false, "/workflow/identifier/DateTime" ) ;
        map.addField ( new String[] { "WORKFLOW", "BEMS" }, "PMBEMN", null, "", "", "", false, true, false, false, "/workflow/BEMS/BEMS_Name" ) ;
        map.addField ( new String[] { "WORKFLOW", "BEMS" }, "PMBEMQ", null, "", "", "", false, true, false, false, "/workflow/BEMS/BEMS_Queue" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "EMPNO", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Number" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "SURNAME", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Surname" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "GIVENAME", null, "", "", "", false, true, false, false, "/workflow/data/Employee/GivenName" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "ADDRESS1", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Address1" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "ADDRESS2", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Address2" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "POSTCODE", null, "", "", "", false, true, false, false, "/workflow/data/Employee/PostCode" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "PHONEHME", null, "", "", "", false, true, false, false, "/workflow/data/Employee/PhoneHome" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "PHONEHME", null, "", "", "", false, true, false, false, "/workflow/data/Employee/PhoneBusiness" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "USTARTDTE", null, "", "", "", false, true, false, false, "/workflow/data/Employee/StartDate" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "DEPTMENT", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Department" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "SECTION", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Section" ) ;
        map.addField ( new String[] { "WORKFLOW", "DATA", "EMPLOYEE" }, "USALARY", null, "", "", "", false, true, false, false, "/workflow/data/Employee/Salary" ) ;
    }

    /*
        Prepare outbound
    */

    public final void prepareOutbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;
        map.addDeclaration ( "xml", "http://www.w3.org/XML/1998/namespace", "/workflow" ) ;

        prepareOutboundListsAndFragments ( map ) ;

        prepareOutboundFields ( map ) ;

        prepareOutboundOrder ( map ) ;
    }

    /*
        Prepare outbound lists and fragments
    */

    private final void prepareOutboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "WORKFLOW" }, null, null, "", "", "", false, true, false, false, "/workflow" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "IDENTIFIER" }, null, null, "", "", "", false, true, false, false, "/workflow/identifier" ) ;
        map.addFragment ( new String[] { "WORKFLOW", "RESPONSE" }, null, null, "", "", "", false, true, false, false, "/workflow/response" ) ;
    }

    /*
        Prepare outbound fields
    */

    private final void prepareOutboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "WORKFLOW", "RESPONSE" }, "RETCODE", null, "", "", "", false, true, false, false, "/workflow/response/status" ) ;
        map.addField ( new String[] { "WORKFLOW", "RESPONSE" }, "BEMSMSG", null, "", "", "", false, true, false, false, "/workflow/response/message" ) ;
    }

    /*
        Prepare outbound order
    */

    private final void prepareOutboundOrder ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addOrder ( "/workflow" ) ;
        map.addOrder ( "/workflow/identifier" ) ;
        map.addOrder ( "/workflow/identifier/Object" ) ;
        map.addOrder ( "/workflow/identifier/Event" ) ;
        map.addOrder ( "/workflow/identifier/Workflow" ) ;
        map.addOrder ( "/workflow/identifier/Case_Number" ) ;
        map.addOrder ( "/workflow/identifier/Workflow_User" ) ;
        map.addOrder ( "/workflow/identifier/DateTime" ) ;
        map.addOrder ( "/workflow/response" ) ;
        map.addOrder ( "/workflow/response/status" ) ;
        map.addOrder ( "/workflow/response/message" ) ;
    }
}
