/**
 * MLQEmployeeServerServiceBindingStubAccessor.java
 *
 * This file was generated by LANSA Integrator SOAP Agent Wizard
 */
package com.lansa.SOAPServer.mlqtutorial ;

public class MLQEmployeeServerServiceBindingStubAccessor implements com.lansa.jsf.soapwizard.LUXOperationAccessor
{
    public org.apache.axis.description.OperationDesc[] getOperations ()
    {
        return MLQEmployeeServerServiceBindingStub._operations ;
    }

    public java.lang.Class getStubClass ()
    {
        return MLQEmployeeServerServiceBindingStub.class ;
    }
}
