/**
 * MLQEmployeeServerService.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.lansa.SOAPServer.mlqtutorial ;

public class MLQEmployeeServerService implements com.lansa.jsm.service.SOAPServerHandler
{

    /*
        Parameter Prepare - MLQGetEmployees ( departmentCode )
    */

    public final void prepareParameter_MLQGETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - MLQGetEmployees ( departmentCode )
    */

    public final void getParameter_MLQGETEMPLOYEES_DEPARTMENTCODE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "DEPTMENT", parameter.getEntity ( null ) ) ;
    }

    /*
        Parameter Prepare - MLQGetEmployees ( sectionCode )
    */

    public final void prepareParameter_MLQGETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPServerParameter parameter ) throws Exception
    {
    }

    /*
        Parameter Get - MLQGetEmployees ( sectionCode )
    */

    public final void getParameter_MLQGETEMPLOYEES_SECTIONCODE ( com.lansa.jsm.service.SOAPServerParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        bind.setFieldValue ( "SECTION", parameter.getEntity ( null ) ) ;
    }

    /*
        Return Parameter Prepare - MLQGetEmployees
    */

    public final void prepareReturn_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPServerResponse response ) throws Exception
    {
        response.prepareParameter ( EMPLOYEE.class, true, true ) ;
        response.prepareFragment ( new String[] { "EMPLOYEE" }, EMPLOYEE.class, true, true, null ) ;
    }

    /*
        Return Parameter Set - MLQGetEmployees
    */

    public final void setReturn_MLQGETEMPLOYEES ( com.lansa.jsm.service.SOAPServerResponseParameter parameter, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
    }

    /*
        Fragment Set - MLQGetEmployees
    */

    public final void setFragment_MLQGETEMPLOYEES_EMPLOYEE ( com.lansa.jsm.service.SOAPServerResponseFragment fragment, com.lansa.jsm.service.SOAPServerBind bind ) throws Exception
    {
        fragment.setEntity ( "employeeID", bind.getFieldValue ( "EMPNO" ), null, null ) ;
        fragment.setEntity ( "firstName", bind.getFieldValue ( "GIVENAME" ), null, null ) ;
        fragment.setEntity ( "lastName", bind.getFieldValue ( "SURNAME" ), null, null ) ;
        fragment.setEntity ( "salary", bind.getFieldValue ( "SALARY" ), null, null ) ;
    }
}
