/**
 * MLQEmployeeServerProvider.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.lansa.SOAPServer.mlqtutorial ;

public interface MLQEmployeeServerProvider
{
    public EMPLOYEE[] MLQGetEmployees ( String departmentCode, String sectionCode ) ;
}
