/**
 * Employee.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.lansa.UHASOAPServer.Tutorial ;

public class Employee implements java.io.Serializable
{
    private String employee_ID ;
    private String firstname ;
    private Double salary ;
    private String surname ;

    /**
     * Sets the employee_ID value for this Employee.
     *
     * @param employee_ID
     */
    public void setEmployee_ID ( String employee_ID )
    {
        this.employee_ID = employee_ID ;
    }

    /**
     * Gets the employee_ID value for this Employee.
     *
     * @return employee_ID
     */
    public String getEmployee_ID ()
    {
        return employee_ID ;
    }

    /**
     * Sets the firstname value for this Employee.
     *
     * @param firstname
     */
    public void setFirstname ( String firstname )
    {
        this.firstname = firstname ;
    }

    /**
     * Gets the firstname value for this Employee.
     *
     * @return firstname
     */
    public String getFirstname ()
    {
        return firstname ;
    }

    /**
     * Sets the salary value for this Employee.
     *
     * @param salary
     */
    public void setSalary ( Double salary )
    {
        this.salary = salary ;
    }

    /**
     * Gets the salary value for this Employee.
     *
     * @return salary
     */
    public Double getSalary ()
    {
        return salary ;
    }

    /**
     * Sets the surname value for this Employee.
     *
     * @param surname
     */
    public void setSurname ( String surname )
    {
        this.surname = surname ;
    }

    /**
     * Gets the surname value for this Employee.
     *
     * @return surname
     */
    public String getSurname ()
    {
        return surname ;
    }

    /*
        Apache Axis Meta-Data
    */

    private static org.apache.axis.description.TypeDesc typeDesc = new org.apache.axis.description.TypeDesc ( Employee.class, true ) ; 

    static
    {
        typeDesc.setXmlType ( new javax.xml.namespace.QName ( "http://Tutorial.UHASOAPServer.lansa.com", "Employee" ) ) ;

        org.apache.axis.description.ElementDesc elemField = null ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "employee_ID" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://Tutorial.UHASOAPServer.lansa.com", "employee_ID" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "string" ) ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "firstname" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://Tutorial.UHASOAPServer.lansa.com", "firstname" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "string" ) ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "salary" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://Tutorial.UHASOAPServer.lansa.com", "salary" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "double" ) ) ;
        elemField.setMinOccurs ( 0 ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;

        elemField = new org.apache.axis.description.ElementDesc () ;
        elemField.setFieldName ( "surname" ) ;
        elemField.setXmlName ( new javax.xml.namespace.QName ( "http://Tutorial.UHASOAPServer.lansa.com", "surname" ) ) ;
        elemField.setXmlType ( new javax.xml.namespace.QName ( "http://www.w3.org/2001/XMLSchema", "string" ) ) ;
        elemField.setNillable ( true ) ;
        typeDesc.addFieldDesc ( elemField ) ;
    }

    public static org.apache.axis.description.TypeDesc getTypeDesc ()
    {
        return typeDesc ;
    }

    public static org.apache.axis.encoding.Serializer getSerializer ( java.lang.String _mechType, java.lang.Class _javaType, javax.xml.namespace.QName _xmlType )
    {
        return new org.apache.axis.encoding.ser.BeanSerializer ( _javaType, _xmlType, typeDesc ) ;
    }

    public static org.apache.axis.encoding.Deserializer getDeserializer ( java.lang.String _mechType, java.lang.Class _javaType, javax.xml.namespace.QName _xmlType )
    {
        return new org.apache.axis.encoding.ser.BeanDeserializer ( _javaType, _xmlType, typeDesc ) ;
    }
}
