/**
 * UHAEmployeeServerProvider.java
 *
 * This file was generated by LANSA Integrator SOAP Server Wizard
 */
package com.lansa.UHASOAPServer.Tutorial ;

public interface UHAEmployeeServerProvider
{
    public void noop (  ) ;
    public Employee[] getEmployees ( String department_code, String section_code ) ;
}
