/**
 * MLQPRO04_requestService.java
 *
 * This file was generated by LANSA Integrator XMLBind Wizard
 */
package com.mlqlansa.service.xml ;

public class MLQPRO04_requestService implements com.lansa.jsm.service.XMLBindHandler
{

    /*
        Prepare inbound
    */

    public final void prepareInbound ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.setLocale ( "" ) ;
        map.setScript ( "" ) ;
        map.addAlias ( "ns0", "http://www.w3.org/XML/1998/namespace" ) ;

        prepareInboundListsAndFragments ( map ) ;

        prepareInboundFields ( map ) ;
    }

    /*
        Prepare inbound lists and fragments
    */

    private final void prepareInboundListsAndFragments ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addFragment ( new String[] { "DEPARTMENTREQUEST" }, null, null, "", "", "", false, true, false, false, "/DepartmentRequest" ) ;
    }

    /*
        Prepare inbound fields
    */

    private final void prepareInboundFields ( com.lansa.jsm.service.XMLBindMap map )
    {
        map.addField ( new String[] { "DEPARTMENTREQUEST" }, "DEPTMENT", null, "", "", "", false, true, false, false, "/DepartmentRequest/DepartmentCode" ) ;
    }

    /*
        Prepare outbound
    */

    public final void prepareOutbound ( com.lansa.jsm.service.XMLBindMap map )
    {
    }
}
